[package]
name = "snake-maze"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.19.3"
rayon = "1.5.1"
rand = "0.8.4"
soloud = "0.4.4"